export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAIL = "PROJECT_LIST_FAIL";

export const PROJECT_BUILDER_REQUEST = "PROJECT_BUILDER_REQUEST";
export const PROJECT_BUILDER_SUCCESS = "PROJECT_BUILDER_SUCCESS";
export const PROJECT_BUILDER_FAIL = "PROJECT_BUILDER_FAIL";
