export const TEACHER_STUDENT_PROFILES_REQUEST = "TEACHER_STUDENT_PROFILES_REQUEST";
export const TEACHER_STUDENT_PROFILES_SUCCESS = "TEACHER_STUDENT_PROFILES_SUCCESS";
export const TEACHER_STUDENT_PROFILES_FAIL = "TEACHER_STUDENT_PROFILES_FAIL";

export const TEACHER_HELPREQ_REQUEST = "TEACHER_HELPREQ_REQUEST";
export const TEACHER_HELPREQ_SUCCESS = "TEACHER_HELPREQ_SUCCESS";
export const TEACHER_HELPREQ_FAIL = "TEACHER_HELPREQ_FAIL";

export const TEACHER_PROGRESS_REQUEST = "TEACHER_PROGRESS_REQUEST";
export const TEACHER_PROGRESS_SUCCESS = "TEACHER_PROGRESS_SUCCESS";
export const TEACHER_PROGRESS_FAIL = "TEACHER_PROGRESS_FAIL";

export const TEACHER_MARKHELP_REQUEST = "TEACHER_MARKHELP_REQUEST";
export const TEACHER_MARKHELP_SUCCESS = "TEACHER_MARKHELP_SUCCESS";
export const TEACHER_MARKHELP_FAIL = "TEACHER_MARKHELP_FAIL";

export const TEACHER_SUBMISSION_REQUEST = "TEACHER_SUBMISSION_REQUEST";
export const TEACHER_SUBMISSION_SUCCESS = "TEACHER_SUBMISSION_SUCCESS";
export const TEACHER_SUBMISSION_FAIL = "TEACHER_SUBMISSION_FAIL";

export const TEACHER_MARKSUBMISSION_REQUEST = "TEACHER_MARKSUBMISSION_REQUEST";
export const TEACHER_MARKSUBMISSION_SUCCESS = "TEACHER_MARKSUBMISSION_SUCCESS";
export const TEACHER_MARKSUBMISSION_FAIL = "TEACHER_MARKSUBMISSION_FAIL";
